export const TYPE_MAP = {
    p_bln: 'Boolean',
    p_int: 'Integer',
    p_fin: 'Finite',
    p_big: 'BigInt',
    p_str: 'String',
    p_sym: 'Symbol',
    p:     'Primitive',

    o_obj: 'PlainObject',
    o_ary: 'Array',
    o_fn_arrow_a: 'AsyncArrowFunction',
    o_fn_arrow_s: 'SyncArrowFunction',
    o_fn_arrow:   'ArrowFunction',
    o_fn_bound:   'BoundFunction',
    o_fn_native:  'NativeFunction',
    o_fn_a:       'AsyncFunction',
    o_fn_g:       'GeneratorFunction',
    o_fn_ag:      'AsyncGeneratorFunction',
    o_fn_s:       'SyncFunction',
    o_fn_anonymous: 'AnonymousFunction',
    o_fn:         'Function',
    
    o_cls_es6:    (v, C) => 'ES6.Class' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_cls_es5:    (v, C) => 'ES5.Class' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_cls_native: (v, C) => 'NativeClass' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_cls:        'Class',
    
    o_ins_es6:    (v, C) => 'ES6.Instance' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_ins_es5:    (v, C) => 'ES5.Instance' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_ins_native: (v, C) => 'NativeInstance' + (C ? `<${C.name || '(Anonymous)'}>` : ''),
    o_ins:        'Instance',
    
    o_des_d_v:    'Descriptor.Data.Value',
    o_des_d_m:    'Descriptor.Data.Method',
    o_des_d:      'Descriptor.Data',
    o_des_a_g:    'Descriptor.Access.Get',
    o_des_a_s:    'Descriptor.Access.Set',
    o_des_a_gs:   'Descriptor.Access.GetSet',
    o_des_a:      'Descriptor.Access',
    o_des:        'Descriptor',
    
    o_md_a:       'AsyncMethod',
    o_md_g:       'GeneratorMethod',
    o_md_ag:      'AsyncGeneratorMethod',
    o_md_s:       'SyncMethod',
    o_md:         'Method',
    o:            'Object',

    d_und:        'Undefined',
    d_nul:        'Null',
    d_num_nan:    'NaN',
    d_num_inf:    'Infinity',
    d_num_pinf:   'PositiveInfinity',
    d_num_ninf:   'NegativeInfinity',
    d_num_oint:   'OverInteger',
    d_num_ofin:   'OverFinite',
    d_num:        'DangerNumber',
    d_obj_boxed:  'BoxedPrimitive',
    d_obj_noneProto: 'NonePrototypesObject',
    d_obj_prototyped: 'PrototypedObject',
    d_obj:        'DangerObject',
    d:            'Danger'
};
