export const baseTypeCases = [
    { name: "undefined", value: undefined, expectedKey: "und" },
    { name: "boolean", value: true, expectedKey: "bln" },
    { name: "bigint", value: 10n, expectedKey: "big" },
    { name: "string", value: "text", expectedKey: "str" },
    { name: "symbol", value: Symbol(), expectedKey: "sym" },
    { name: "function", value: () => {}, expectedKey: "fn" },
    { name: "object", value: {}, expectedKey: "obj" },
    { name: "null", value: null, expectedKey: "nul" },
    { name: "safe integer", value: 42, expectedKey: "num" },
    { name: "safe float / decimal", value: 100.5, expectedKey: "num" },
    { name: "NaN", value: NaN, expectedKey: "num" },
    { name: "positive Infinity", value: Infinity, expectedKey: "num" },
    { name: "negative Infinity", value: -Infinity, expectedKey: "num" },
    { name: "overflow int (MAX + 1)", value: Number.MAX_SAFE_INTEGER + 1, expectedKey: "num" },
    { name: "overflow int (MIN - 1)", value: Number.MIN_SAFE_INTEGER - 1, expectedKey: "num" },
];

export const leafTypeCases = [
    { name: "undefined", value: undefined, tofPath: "und" },
    { name: "boolean", value: true, tofPath: "bln" },
    { name: "bigint", value: 10n, tofPath: "big" },
    { name: "string", value: "text", tofPath: "str" },
    { name: "symbol", value: Symbol(), tofPath: "sym" },
    { name: "function", value: () => {}, tofPath: "fn" },
    { name: "object", value: {}, tofPath: "obj" },
    { name: "null", value: null, tofPath: "nul" },
    { name: "safe integer", value: 100, tofPath: "num.int" },
    //{ name: "safe float / decimal", value: 100.5, tofPath: "num.fin" },
    { name: "safe float / decimal", value: 100.5, tofPath: "num.bin.flt" },
    { name: "NaN", value: NaN, tofPath: "num.nan" },
    { name: "positive Infinity", value: Infinity, tofPath: "num.inf.p" },
    { name: "negative Infinity", value: -Infinity, tofPath: "num.inf.n" },
//    { name: "overflow int (MAX + 1)", value: Number.MAX_SAFE_INTEGER + 1, tofPath: "num.over" },
//    { name: "overflow int (MIN - 1)", value: Number.MIN_SAFE_INTEGER - 1, tofPath: "num.over" },
    { name: "overflow int (MAX + 1)", value: Number.MAX_SAFE_INTEGER + 1, tofPath: "num.bin.over" },
    { name: "overflow int (MIN - 1)", value: Number.MIN_SAFE_INTEGER - 1, tofPath: "num.bin.over" },
];

export const intermediateTypeCases = [
    { name: "safe int for num", value: 100, path: "num" },
    { name: "safe float for num", value: 100.5, path: "num" },
    { name: "NaN for num", value: NaN, path: "num" },
    { name: "positive Infinity for num", value: Infinity, path: "num" },
    { name: "negative Infinity for num", value: -Infinity, path: "num" },
    { name: "overflow MAX for num", value: Number.MAX_SAFE_INTEGER + 1, path: "num" },
    { name: "overflow MIN for num", value: Number.MIN_SAFE_INTEGER - 1, path: "num" },
    { name: "positive Infinity for num.inf", value: Infinity, path: "num.inf" },
    { name: "negative Infinity for num.inf", value: -Infinity, path: "num.inf" },
];

export const numSubCases = [
    { desc: "safe integer", val: 100, checks: { int: true, bin: false, nan: false, inf: false, over: false } },
    { desc: "MAX_SAFE_INTEGER", val: Number.MAX_SAFE_INTEGER, checks: { int: true, bin: false, nan: false, inf: false, over: false } },
    { desc: "MIN_SAFE_INTEGER", val: Number.MIN_SAFE_INTEGER, checks: { int: true, bin: false, nan: false, inf: false, over: false } },
    { desc: "safe float / decimal", val: 100.5, checks: { int: false, bin: true, nan: false, inf: false, over: false } },
    { desc: "NaN", val: NaN, checks: { int: false, bin: false, nan: true, inf: false, over: false } },
    { desc: "positive Infinity", val: Infinity, checks: { int: false, bin: false, nan: false, inf: true, over: false, p: true, n: false } },
    { desc: "negative Infinity", val: -Infinity, checks: { int: false, bin: false, nan: false, inf: true, over: false, p: false, n: true } },
    { desc: "overflow int (MAX + 1)", val: Number.MAX_SAFE_INTEGER + 1, checks: { int: false, bin: true, nan: false, inf: false, over: true } },
    { desc: "overflow int (MIN - 1)", val: Number.MIN_SAFE_INTEGER - 1, checks: { int: false, bin: true, nan: false, inf: false, over: true } },
];
